[package]
name = "posted-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.1"
actix-web-httpauth = "0.8.1"
argon2 = "0.5.3"
chrono = { version = "0.4.33", features = [ "serde" ] }
dotenv = "0.15.0"
env_logger = "0.10.0"
log = "0.4.20"
redis = { version = "0.25.2", features = [ "async-std-comp" ] }
serde = "1.0.196"
serde_json = "1.0.113"
sqlx = { version = "0.7.3", features = [ "runtime-async-std", "mysql", "chrono" ] }
uuid = {version = "1.7.0", features = [ "v4", "serde" ] }
zeroize = "1.7.0"
